name: fslite-venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
      - setuptools
      - networkx
      - numpy
      - pyarrow
      - pandas
      - scipy
      - scikit-learn
      - psutil
      - pytest
      - matplotlib
